<template><div><h1 id="다양한-linux-생성-샘플" tabindex="-1"><a class="header-anchor" href="#다양한-linux-생성-샘플" aria-hidden="true">#</a> 다양한 Linux 생성 샘플</h1>
<div class="language-ruby line-numbers-mode" data-ext="rb"><pre v-pre class="language-ruby"><code><span class="token comment"># -*- mode: ruby -*-</span>
<span class="token comment"># vi: set ft=ruby :</span>

<span class="token comment"># base image : https://app.vagrantup.com/bento</span>
<span class="token comment"># Cluster IP have to set subnetting on private network subnet of VM</span>

<span class="token variable">$debianip</span> <span class="token operator">=</span> <span class="token number">50</span>
<span class="token variable">$centip</span> <span class="token operator">=</span> <span class="token number">60</span>
<span class="token variable">$suseip</span> <span class="token operator">=</span> <span class="token number">70</span>

debian_cluster <span class="token operator">=</span> <span class="token punctuation">{</span>
  <span class="token string-literal"><span class="token string">"ubuntu"</span></span> <span class="token operator">=></span> <span class="token punctuation">{</span> <span class="token symbol">:image</span> <span class="token operator">=></span> <span class="token string-literal"><span class="token string">"bento/ubuntu-18.04"</span></span><span class="token punctuation">}</span>
<span class="token punctuation">}</span>
cent_cluster <span class="token operator">=</span> <span class="token punctuation">{</span>
  <span class="token string-literal"><span class="token string">"centos"</span></span> <span class="token operator">=></span> <span class="token punctuation">{</span> <span class="token symbol">:image</span> <span class="token operator">=></span> <span class="token string-literal"><span class="token string">"centos/7"</span></span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token string-literal"><span class="token string">"rocky"</span></span> <span class="token operator">=></span> <span class="token punctuation">{</span> <span class="token symbol">:image</span> <span class="token operator">=></span> <span class="token string-literal"><span class="token string">"rockylinux/8"</span></span><span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span>
suse_cluster <span class="token operator">=</span>  <span class="token punctuation">{</span>
  <span class="token string-literal"><span class="token string">"suse"</span></span> <span class="token operator">=></span> <span class="token punctuation">{</span> <span class="token symbol">:image</span> <span class="token operator">=></span> <span class="token string-literal"><span class="token string">"opensuse/Tumbleweed.x86_64"</span></span> <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

Vagrant<span class="token punctuation">.</span>configure<span class="token punctuation">(</span><span class="token string-literal"><span class="token string">"2"</span></span><span class="token punctuation">)</span> <span class="token keyword">do</span> <span class="token operator">|</span>config<span class="token operator">|</span>

  config<span class="token punctuation">.</span>vm<span class="token punctuation">.</span>synced_folder <span class="token string-literal"><span class="token string">'.'</span></span><span class="token punctuation">,</span> <span class="token string-literal"><span class="token string">'/vagrant'</span></span><span class="token punctuation">,</span> <span class="token symbol">disabled</span><span class="token operator">:</span> <span class="token boolean">true</span>

  debian_cluster<span class="token punctuation">.</span>each_with_index <span class="token keyword">do</span> <span class="token operator">|</span><span class="token punctuation">(</span>hostname<span class="token punctuation">,</span> info<span class="token punctuation">)</span><span class="token punctuation">,</span> i<span class="token operator">|</span>
    config<span class="token punctuation">.</span>vm<span class="token punctuation">.</span>define hostname <span class="token keyword">do</span> <span class="token operator">|</span>server<span class="token operator">|</span>
      server<span class="token punctuation">.</span>vm<span class="token punctuation">.</span>box <span class="token operator">=</span> info<span class="token punctuation">[</span><span class="token symbol">:image</span><span class="token punctuation">]</span>
      server<span class="token punctuation">.</span>vm<span class="token punctuation">.</span>hostname <span class="token operator">=</span> hostname
      server<span class="token punctuation">.</span>vm<span class="token punctuation">.</span>network <span class="token string-literal"><span class="token string">"private_network"</span></span><span class="token punctuation">,</span> <span class="token symbol">name</span><span class="token operator">:</span> <span class="token string-literal"><span class="token string">"vboxnet1"</span></span><span class="token punctuation">,</span> <span class="token symbol">ip</span><span class="token operator">:</span> <span class="token string-literal"><span class="token string">"172.28.128.</span><span class="token interpolation"><span class="token delimiter punctuation">#{</span><span class="token content">i <span class="token operator">+</span> <span class="token variable">$debianip</span></span><span class="token delimiter punctuation">}</span></span><span class="token string">"</span></span>

      server<span class="token punctuation">.</span>vm<span class="token punctuation">.</span>provider <span class="token string-literal"><span class="token string">"virtualbox"</span></span> <span class="token keyword">do</span> <span class="token operator">|</span>v<span class="token operator">|</span>
        v<span class="token punctuation">.</span>name <span class="token operator">=</span> hostname
        v<span class="token punctuation">.</span>gui <span class="token operator">=</span> <span class="token boolean">false</span>
        v<span class="token punctuation">.</span>memory <span class="token operator">=</span> <span class="token number">1024</span>
        v<span class="token punctuation">.</span>cpus <span class="token operator">=</span> <span class="token number">1</span>

        v<span class="token punctuation">.</span>customize <span class="token punctuation">[</span><span class="token string-literal"><span class="token string">"modifyvm"</span></span><span class="token punctuation">,</span> <span class="token symbol">:id</span><span class="token punctuation">,</span> <span class="token string-literal"><span class="token string">"--vram"</span></span><span class="token punctuation">,</span> <span class="token string-literal"><span class="token string">"9"</span></span><span class="token punctuation">]</span>
      <span class="token keyword">end</span> <span class="token comment"># end provider</span>
    <span class="token keyword">end</span> <span class="token comment"># end config</span>
  <span class="token keyword">end</span> <span class="token comment"># end cluster foreach</span>

  suse_cluster<span class="token punctuation">.</span>each_with_index <span class="token keyword">do</span> <span class="token operator">|</span><span class="token punctuation">(</span>hostname<span class="token punctuation">,</span> info<span class="token punctuation">)</span><span class="token punctuation">,</span> i<span class="token operator">|</span>
    config<span class="token punctuation">.</span>vm<span class="token punctuation">.</span>define hostname <span class="token keyword">do</span> <span class="token operator">|</span>server<span class="token operator">|</span>
      server<span class="token punctuation">.</span>vm<span class="token punctuation">.</span>box <span class="token operator">=</span> info<span class="token punctuation">[</span><span class="token symbol">:image</span><span class="token punctuation">]</span>
      server<span class="token punctuation">.</span>vm<span class="token punctuation">.</span>hostname <span class="token operator">=</span> hostname
      server<span class="token punctuation">.</span>vm<span class="token punctuation">.</span>network <span class="token string-literal"><span class="token string">"private_network"</span></span><span class="token punctuation">,</span> <span class="token symbol">name</span><span class="token operator">:</span> <span class="token string-literal"><span class="token string">"vboxnet1"</span></span><span class="token punctuation">,</span> <span class="token symbol">ip</span><span class="token operator">:</span> <span class="token string-literal"><span class="token string">"172.28.128.</span><span class="token interpolation"><span class="token delimiter punctuation">#{</span><span class="token content">i <span class="token operator">+</span> <span class="token variable">$suseip</span></span><span class="token delimiter punctuation">}</span></span><span class="token string">"</span></span>
      server<span class="token punctuation">.</span>vm<span class="token punctuation">.</span>provider <span class="token string-literal"><span class="token string">"virtualbox"</span></span> <span class="token keyword">do</span> <span class="token operator">|</span>v<span class="token operator">|</span>
        v<span class="token punctuation">.</span>name <span class="token operator">=</span> hostname
        v<span class="token punctuation">.</span>gui <span class="token operator">=</span> <span class="token boolean">false</span>
        v<span class="token punctuation">.</span>memory <span class="token operator">=</span> <span class="token number">1024</span>
        v<span class="token punctuation">.</span>cpus <span class="token operator">=</span> <span class="token number">1</span>

        v<span class="token punctuation">.</span>customize <span class="token punctuation">[</span><span class="token string-literal"><span class="token string">"modifyvm"</span></span><span class="token punctuation">,</span> <span class="token symbol">:id</span><span class="token punctuation">,</span> <span class="token string-literal"><span class="token string">"--vram"</span></span><span class="token punctuation">,</span> <span class="token string-literal"><span class="token string">"9"</span></span><span class="token punctuation">]</span>
      <span class="token keyword">end</span> <span class="token comment"># end provider</span>
    <span class="token keyword">end</span> <span class="token comment"># end config</span>
  <span class="token keyword">end</span> <span class="token comment"># end cluster foreach</span>

  cent_cluster<span class="token punctuation">.</span>each_with_index <span class="token keyword">do</span> <span class="token operator">|</span><span class="token punctuation">(</span>hostname<span class="token punctuation">,</span> info<span class="token punctuation">)</span><span class="token punctuation">,</span> i<span class="token operator">|</span>
    config<span class="token punctuation">.</span>vm<span class="token punctuation">.</span>define hostname <span class="token keyword">do</span> <span class="token operator">|</span>server<span class="token operator">|</span>
      server<span class="token punctuation">.</span>vm<span class="token punctuation">.</span>box <span class="token operator">=</span> info<span class="token punctuation">[</span><span class="token symbol">:image</span><span class="token punctuation">]</span>
      server<span class="token punctuation">.</span>vm<span class="token punctuation">.</span>hostname <span class="token operator">=</span> hostname
      server<span class="token punctuation">.</span>vm<span class="token punctuation">.</span>network <span class="token string-literal"><span class="token string">"private_network"</span></span><span class="token punctuation">,</span> <span class="token symbol">name</span><span class="token operator">:</span> <span class="token string-literal"><span class="token string">"vboxnet1"</span></span><span class="token punctuation">,</span> <span class="token symbol">ip</span><span class="token operator">:</span> <span class="token string-literal"><span class="token string">"172.28.128.</span><span class="token interpolation"><span class="token delimiter punctuation">#{</span><span class="token content">i <span class="token operator">+</span> <span class="token variable">$centip</span></span><span class="token delimiter punctuation">}</span></span><span class="token string">"</span></span>

      server<span class="token punctuation">.</span>vm<span class="token punctuation">.</span>provider <span class="token string-literal"><span class="token string">"virtualbox"</span></span> <span class="token keyword">do</span> <span class="token operator">|</span>v<span class="token operator">|</span>
        v<span class="token punctuation">.</span>name <span class="token operator">=</span> hostname
        v<span class="token punctuation">.</span>gui <span class="token operator">=</span> <span class="token boolean">false</span>
        v<span class="token punctuation">.</span>memory <span class="token operator">=</span> <span class="token number">1024</span>
        v<span class="token punctuation">.</span>cpus <span class="token operator">=</span> <span class="token number">1</span>

        v<span class="token punctuation">.</span>customize <span class="token punctuation">[</span><span class="token string-literal"><span class="token string">"modifyvm"</span></span><span class="token punctuation">,</span> <span class="token symbol">:id</span><span class="token punctuation">,</span> <span class="token string-literal"><span class="token string">"--vram"</span></span><span class="token punctuation">,</span> <span class="token string-literal"><span class="token string">"9"</span></span><span class="token punctuation">]</span>
      <span class="token keyword">end</span> <span class="token comment"># end provider</span>
    <span class="token keyword">end</span> <span class="token comment"># end config</span>
  <span class="token keyword">end</span> <span class="token comment"># end cluster foreach</span>
  
<span class="token keyword">end</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


