<template><div><h1 id="graceful-shutdown-적용-kill-signal" tabindex="-1"><a class="header-anchor" href="#graceful-shutdown-적용-kill-signal" aria-hidden="true">#</a> Graceful Shutdown 적용 (kill_signal)</h1>
<blockquote>
<p>GitHub 리소스 : <a href="https://github.com/Great-Stone/nomad-springboot-graceful-shutdown" target="_blank" rel="noopener noreferrer">https://github.com/Great-Stone/nomad-springboot-graceful-shutdown<ExternalLinkIcon/></a></p>
</blockquote>
<h2 id="테스트-환경" tabindex="-1"><a class="header-anchor" href="#테스트-환경" aria-hidden="true">#</a> 테스트 환경</h2>
<ul>
<li>Gradle 7.4.2</li>
<li>Java 11</li>
<li>Spring Boot 2.7.7</li>
<li>Nomad 1.4.3</li>
</ul>
<h2 id="spring-boot-리뷰" tabindex="-1"><a class="header-anchor" href="#spring-boot-리뷰" aria-hidden="true">#</a> Spring Boot 리뷰</h2>
<h3 id="application-yml-구성" tabindex="-1"><a class="header-anchor" href="#application-yml-구성" aria-hidden="true">#</a> <code v-pre>application.yml</code> 구성</h3>
<div class="language-yaml line-numbers-mode" data-ext="yml"><pre v-pre class="language-yaml"><code><span class="token key atrule">server</span><span class="token punctuation">:</span>
  <span class="token key atrule">port</span><span class="token punctuation">:</span> <span class="token number">8080</span>
  <span class="token key atrule">shutdown</span><span class="token punctuation">:</span> graceful 
<span class="token key atrule">spring</span><span class="token punctuation">:</span>
  <span class="token key atrule">lifecycle</span><span class="token punctuation">:</span>
    <span class="token key atrule">timeout-per-shutdown-phase</span><span class="token punctuation">:</span> 35s <span class="token comment"># Default 30s</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li><code v-pre>server.shutdown</code>에 <code v-pre>graceful</code> 정의 필요</li>
<li><code v-pre>spring.lifecycle.timeout-per-shutdown-phase</code>에 Graceful Shutdown 요청시 지연 시간 설정</li>
</ul>
<h3 id="graceful-shutdown-테스트" tabindex="-1"><a class="header-anchor" href="#graceful-shutdown-테스트" aria-hidden="true">#</a> Graceful Shutdown 테스트</h3>
<ul>
<li>
<p>테스트는 빌드(<code v-pre>gradle build</code>) 후 해당 jar파일에 대해 실행</p>
</li>
<li>
<p>실행 커맨드 예시 : <code v-pre>java -jar ./build/libs/demo-0.0.1-SNAPSHOT.jar</code></p>
</li>
<li>
<p>테스트 API : <code v-pre>http://localhost:8080/test/1</code></p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code>$ <span class="token function">curl</span> http://localhost:8080/test/1
<span class="token punctuation">(</span>코드에서 지정한 20000ms 지연<span class="token punctuation">)</span>
Process Success <span class="token operator">!</span><span class="token operator">!</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></li>
<li>
<p>Graceful Shutdown 종료를 위해 <code v-pre>kill -15 &lt;PID&gt;</code> 형태의 시그널 전달 필요</p>
<ul>
<li>KILL(<code v-pre>-9</code>)대신 TERM(<code v-pre>-15</code>)를 사용</li>
<li>KILL(SIGKILL) : 무조건적인 즉각적 종료</li>
<li>TERM(SIGTERM) : 자연스러운 실행 종료, 정상 종료 작업 처리 후 끝냄</li>
</ul>
</li>
<li>
<p>SIGTERM 사용시 종료 메시지 확인 및 정상 응답 확인</p>
<div class="language-log line-numbers-mode" data-ext="log"><pre v-pre class="language-log"><code>  <span class="token punctuation">.</span>   ____          _            __ _ _
<span class="token operator">/</span>\\ <span class="token operator">/</span> ___'_ __ _ _<span class="token operator">(</span>_<span class="token operator">)</span>_ __  __ _ \ \ \ \
<span class="token operator">(</span> <span class="token operator">(</span> <span class="token operator">)</span>\___ <span class="token operator">|</span> <span class="token string">'_ | '</span>_<span class="token operator">|</span> <span class="token operator">|</span> '_ \<span class="token operator">/</span> _` <span class="token operator">|</span> \ \ \ \
\\<span class="token operator">/</span>  ___<span class="token operator">)</span><span class="token operator">|</span> <span class="token operator">|</span>_<span class="token operator">)</span><span class="token operator">|</span> <span class="token operator">|</span> <span class="token operator">|</span> <span class="token operator">|</span> <span class="token operator">|</span> <span class="token operator">|</span><span class="token operator">|</span> <span class="token operator">(</span>_<span class="token operator">|</span> <span class="token operator">|</span>  <span class="token operator">)</span> <span class="token operator">)</span> <span class="token operator">)</span> <span class="token operator">)</span>
  '  <span class="token operator">|</span>____<span class="token operator">|</span> <span class="token punctuation">.</span>__<span class="token operator">|</span>_<span class="token operator">|</span> <span class="token operator">|</span>_<span class="token operator">|</span>_<span class="token operator">|</span> <span class="token operator">|</span>_\__<span class="token punctuation">,</span> <span class="token operator">|</span> <span class="token operator">/</span> <span class="token operator">/</span> <span class="token operator">/</span> <span class="token operator">/</span>
<span class="token separator comment">=========</span><span class="token operator">|</span>_<span class="token operator">|</span><span class="token separator comment">==============</span><span class="token operator">|</span>___<span class="token operator">/</span><span class="token operator">=</span><span class="token operator">/</span>_<span class="token operator">/</span>_<span class="token operator">/</span>_<span class="token operator">/</span>
<span class="token operator">:</span><span class="token operator">:</span> Spring Boot <span class="token operator">:</span><span class="token operator">:</span>                <span class="token operator">(</span><span class="token number">v2.7.7</span><span class="token operator">)</span>

<span class="token date number">2023-01-12</span> <span class="token time number">14:10:14.572</span>  <span class="token level info keyword">INFO</span> <span class="token number">45334</span> <span class="token separator comment">---</span> <span class="token punctuation">[</span>           main<span class="token punctuation">]</span> com<span class="token punctuation">.</span>example<span class="token punctuation">.</span>demo<span class="token punctuation">.</span>DemoApplication         <span class="token operator">:</span> Starting DemoApplication using Java <span class="token ip-address constant">11.0.14.1</span> on gs<span class="token operator">-</span>C02CT3ZFML85 with PID <span class="token number">45334</span> <span class="token operator">(</span><span class="token file-path string">/private/var/folders/5r/8y6t82xd1h183tq1l_whv8yw0000gn/T/NomadClient2000479524/d5d8f4a6-4fd7-87ea-b40b-93f0227371db/boot/local/uc</span> started by gs in <span class="token file-path string">/private/var/folders/5r/8y6t82xd1h183tq1l_whv8yw0000gn/T/NomadClient2000479524/d5d8f4a6-4fd7-87ea-b40b-93f0227371db/boot</span><span class="token operator">)</span>
<span class="token date number">2023-01-12</span> <span class="token time number">14:10:14.575</span>  <span class="token level info keyword">INFO</span> <span class="token number">45334</span> <span class="token separator comment">---</span> <span class="token punctuation">[</span>           main<span class="token punctuation">]</span> com<span class="token punctuation">.</span>example<span class="token punctuation">.</span>demo<span class="token punctuation">.</span>DemoApplication         <span class="token operator">:</span> No active profile set<span class="token punctuation">,</span> falling back to <span class="token number">1</span> default profile<span class="token operator">:</span> <span class="token string">"default"</span>
<span class="token date number">2023-01-12</span> <span class="token time number">14:10:15.462</span>  <span class="token level info keyword">INFO</span> <span class="token number">45334</span> <span class="token separator comment">---</span> <span class="token punctuation">[</span>           main<span class="token punctuation">]</span> o<span class="token punctuation">.</span>s<span class="token punctuation">.</span>b<span class="token punctuation">.</span>w<span class="token punctuation">.</span>embedded<span class="token punctuation">.</span>tomcat<span class="token punctuation">.</span>TomcatWebServer  <span class="token operator">:</span> Tomcat initialized with port<span class="token operator">(</span>s<span class="token operator">)</span><span class="token operator">:</span> <span class="token number">8080</span> <span class="token operator">(</span>http<span class="token operator">)</span>
<span class="token date number">2023-01-12</span> <span class="token time number">14:10:15.475</span>  <span class="token level info keyword">INFO</span> <span class="token number">45334</span> <span class="token separator comment">---</span> <span class="token punctuation">[</span>           main<span class="token punctuation">]</span> o<span class="token punctuation">.</span>apache<span class="token punctuation">.</span>catalina<span class="token punctuation">.</span>core<span class="token punctuation">.</span>StandardService   <span class="token operator">:</span> Starting service <span class="token punctuation">[</span>Tomcat<span class="token punctuation">]</span>
<span class="token date number">2023-01-12</span> <span class="token time number">14:10:15.476</span>  <span class="token level info keyword">INFO</span> <span class="token number">45334</span> <span class="token separator comment">---</span> <span class="token punctuation">[</span>           main<span class="token punctuation">]</span> org<span class="token punctuation">.</span>apache<span class="token punctuation">.</span>catalina<span class="token punctuation">.</span>core<span class="token punctuation">.</span>StandardEngine  <span class="token operator">:</span> Starting Servlet engine<span class="token operator">:</span> <span class="token punctuation">[</span>Apache Tomcat<span class="token operator">/</span><span class="token number">9.0.70</span><span class="token punctuation">]</span>
<span class="token date number">2023-01-12</span> <span class="token time number">14:10:15.553</span>  <span class="token level info keyword">INFO</span> <span class="token number">45334</span> <span class="token separator comment">---</span> <span class="token punctuation">[</span>           main<span class="token punctuation">]</span> o<span class="token punctuation">.</span>a<span class="token punctuation">.</span>c<span class="token punctuation">.</span>c<span class="token punctuation">.</span>C<span class="token punctuation">.</span><span class="token punctuation">[</span>Tomcat<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token punctuation">[</span>localhost<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token punctuation">[</span><span class="token operator">/</span><span class="token punctuation">]</span>       <span class="token operator">:</span> Initializing Spring embedded WebApplicationContext
<span class="token date number">2023-01-12</span> <span class="token time number">14:10:15.553</span>  <span class="token level info keyword">INFO</span> <span class="token number">45334</span> <span class="token separator comment">---</span> <span class="token punctuation">[</span>           main<span class="token punctuation">]</span> w<span class="token punctuation">.</span>s<span class="token punctuation">.</span>c<span class="token punctuation">.</span>ServletWebServerApplicationContext <span class="token operator">:</span> Root WebApplicationContext<span class="token operator">:</span> initialization completed in <span class="token number">922</span> ms
<span class="token date number">2023-01-12</span> <span class="token time number">14:10:15.948</span>  <span class="token level info keyword">INFO</span> <span class="token number">45334</span> <span class="token separator comment">---</span> <span class="token punctuation">[</span>           main<span class="token punctuation">]</span> o<span class="token punctuation">.</span>s<span class="token punctuation">.</span>b<span class="token punctuation">.</span>w<span class="token punctuation">.</span>embedded<span class="token punctuation">.</span>tomcat<span class="token punctuation">.</span>TomcatWebServer  <span class="token operator">:</span> Tomcat started on port<span class="token operator">(</span>s<span class="token operator">)</span><span class="token operator">:</span> <span class="token number">8080</span> <span class="token operator">(</span>http<span class="token operator">)</span> with context path <span class="token string">''</span>
<span class="token date number">2023-01-12</span> <span class="token time number">14:10:15.957</span>  <span class="token level info keyword">INFO</span> <span class="token number">45334</span> <span class="token separator comment">---</span> <span class="token punctuation">[</span>           main<span class="token punctuation">]</span> com<span class="token punctuation">.</span>example<span class="token punctuation">.</span>demo<span class="token punctuation">.</span>DemoApplication         <span class="token operator">:</span> Started DemoApplication in <span class="token number">1.876</span> seconds <span class="token operator">(</span>JVM running for <span class="token number">2.331</span><span class="token operator">)</span>
<span class="token date number">2023-01-12</span> <span class="token time number">14:10:26.982</span>  <span class="token level info keyword">INFO</span> <span class="token number">45334</span> <span class="token separator comment">---</span> <span class="token punctuation">[</span>nio<span class="token operator">-</span><span class="token number">8080</span><span class="token operator">-</span>exec<span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">]</span> o<span class="token punctuation">.</span>a<span class="token punctuation">.</span>c<span class="token punctuation">.</span>c<span class="token punctuation">.</span>C<span class="token punctuation">.</span><span class="token punctuation">[</span>Tomcat<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token punctuation">[</span>localhost<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token punctuation">[</span><span class="token operator">/</span><span class="token punctuation">]</span>       <span class="token operator">:</span> Initializing Spring DispatcherServlet <span class="token string">'dispatcherServlet'</span>
<span class="token date number">2023-01-12</span> <span class="token time number">14:10:26.982</span>  <span class="token level info keyword">INFO</span> <span class="token number">45334</span> <span class="token separator comment">---</span> <span class="token punctuation">[</span>nio<span class="token operator">-</span><span class="token number">8080</span><span class="token operator">-</span>exec<span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">]</span> o<span class="token punctuation">.</span>s<span class="token punctuation">.</span>web<span class="token punctuation">.</span>servlet<span class="token punctuation">.</span>DispatcherServlet        <span class="token operator">:</span> Initializing Servlet <span class="token string">'dispatcherServlet'</span>
<span class="token date number">2023-01-12</span> <span class="token time number">14:10:26.983</span>  <span class="token level info keyword">INFO</span> <span class="token number">45334</span> <span class="token separator comment">---</span> <span class="token punctuation">[</span>nio<span class="token operator">-</span><span class="token number">8080</span><span class="token operator">-</span>exec<span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">]</span> o<span class="token punctuation">.</span>s<span class="token punctuation">.</span>web<span class="token punctuation">.</span>servlet<span class="token punctuation">.</span>DispatcherServlet        <span class="token operator">:</span> Completed initialization in <span class="token number">1</span> ms
<span class="token date number">2023-01-12</span> <span class="token time number">14:10:27.022</span>  <span class="token level info keyword">INFO</span> <span class="token number">45334</span> <span class="token separator comment">---</span> <span class="token punctuation">[</span>nio<span class="token operator">-</span><span class="token number">8080</span><span class="token operator">-</span>exec<span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">]</span> com<span class="token punctuation">.</span>example<span class="token punctuation">.</span>demo<span class="token punctuation">.</span>TestController          <span class="token operator">:</span> <span class="token separator comment">==========================</span> Start Process <span class="token operator">-</span><span class="token operator">></span> Process Number<span class="token operator">:</span> <span class="token number">4</span>
<span class="token date number">2023-01-12</span> <span class="token time number">14:10:32.243</span>  <span class="token level info keyword">INFO</span> <span class="token number">45334</span> <span class="token separator comment">---</span> <span class="token punctuation">[</span>ionShutdownHook<span class="token punctuation">]</span> o<span class="token punctuation">.</span>s<span class="token punctuation">.</span>b<span class="token punctuation">.</span>w<span class="token punctuation">.</span>e<span class="token punctuation">.</span>tomcat<span class="token punctuation">.</span>GracefulShutdown        <span class="token operator">:</span> Commencing graceful shutdown<span class="token punctuation">.</span> Waiting for active requests to complete
<span class="token date number">2023-01-12</span> <span class="token time number">14:10:47.030</span>  <span class="token level info keyword">INFO</span> <span class="token number">45334</span> <span class="token separator comment">---</span> <span class="token punctuation">[</span>nio<span class="token operator">-</span><span class="token number">8080</span><span class="token operator">-</span>exec<span class="token operator">-</span><span class="token number">1</span><span class="token punctuation">]</span> com<span class="token punctuation">.</span>example<span class="token punctuation">.</span>demo<span class="token punctuation">.</span>TestController          <span class="token operator">:</span> <span class="token separator comment">==========================</span> End Process <span class="token operator">-</span><span class="token operator">></span> Process Number<span class="token operator">:</span> <span class="token number">4</span>
<span class="token date number">2023-01-12</span> <span class="token time number">14:10:47.089</span>  <span class="token level info keyword">INFO</span> <span class="token number">45334</span> <span class="token separator comment">---</span> <span class="token punctuation">[</span>tomcat<span class="token operator">-</span>shutdown<span class="token punctuation">]</span> o<span class="token punctuation">.</span>s<span class="token punctuation">.</span>b<span class="token punctuation">.</span>w<span class="token punctuation">.</span>e<span class="token punctuation">.</span>tomcat<span class="token punctuation">.</span>GracefulShutdown        <span class="token operator">:</span> Graceful shutdown complete
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>Sleep이 20초 소요되는 작업으로, 응답 중간에 SIGTERM 요청시 <code v-pre>Commencing graceful shutdown. Waiting for active requests to complete</code> 메시지 출력</li>
<li>정상 종료 후 <code v-pre>Graceful shutdown complete</code> 메시지 출력</li>
</ul>
</li>
</ul>
<h2 id="nomad-job-리뷰" tabindex="-1"><a class="header-anchor" href="#nomad-job-리뷰" aria-hidden="true">#</a> Nomad Job 리뷰</h2>
<div class="language-hcl line-numbers-mode" data-ext="hcl"><pre v-pre class="language-hcl"><code>job <span class="token string">"graceful"</span> <span class="token punctuation">{</span>
  <span class="token property">datacenters</span> <span class="token punctuation">=</span> <span class="token punctuation">[</span><span class="token string">"dc1"</span><span class="token punctuation">]</span>
  
  group <span class="token string">"java"</span> <span class="token punctuation">{</span>
    task <span class="token string">"boot"</span> <span class="token punctuation">{</span>
      <span class="token property">driver</span> <span class="token punctuation">=</span> <span class="token string">"java"</span>
      
      <span class="token property">kill_timeout</span> <span class="token punctuation">=</span> <span class="token string">"40s"</span>
      <span class="token property">kill_signal</span> <span class="token punctuation">=</span> <span class="token string">"SIGTERM"</span>

      <span class="token keyword">config</span> <span class="token punctuation">{</span>
        <span class="token property">jar_path</span>    <span class="token punctuation">=</span> <span class="token string">"local/demo-0.0.1-SNAPSHOT.jar"</span>
        <span class="token property">jvm_options</span> <span class="token punctuation">=</span> <span class="token punctuation">[</span><span class="token string">"-Xmx2048m"</span>, <span class="token string">"-Xms256m"</span><span class="token punctuation">]</span>
      <span class="token punctuation">}</span>

      <span class="token keyword">artifact</span> <span class="token punctuation">{</span>
        <span class="token property">source</span> <span class="token punctuation">=</span> <span class="token string">"https://github.com/Great-Stone/nomad-springboot-graceful-shutdown/releases/download/0.0.1/demo-0.0.1-SNAPSHOT.jar"</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>Nomad의 기본 종료는 <code v-pre>SIGKILL</code>이므로 task 정의에서 <code v-pre>kill_signal</code>을 <code v-pre>SIGTERM</code>으로 변경 필요</li>
<li><code v-pre>kill_timeout</code> 기본 값이 5초 이므로, Graceful Shutdown을 적용하려는 애플리케이션의 정의 보다 크게 설정 필요</li>
</ul>
<figure><img src="@source/04-HashiCorp/07-Nomad/04-UseCase/image/job_stop_log.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
</div></template>


