<template><div><h1 id="terraform-enterprise-사용자-비밀번호-변경" tabindex="-1"><a class="header-anchor" href="#terraform-enterprise-사용자-비밀번호-변경" aria-hidden="true">#</a> Terraform Enterprise 사용자 비밀번호 변경</h1>
<p>Terraform Enterprise를 사용할 때, UI(https://TFE_SERVER) 상으로 접속할 수 없는 상황에서 비밀번호 변경이 필요한 경우, 아래와 같이 작업할 수 있다.</p>
<h2 id="admin-계정의-경우" tabindex="-1"><a class="header-anchor" href="#admin-계정의-경우" aria-hidden="true">#</a> Admin 계정의 경우</h2>
<p>다음과 같이 수정 가능.</p>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token comment"># 이전 버전의 TFE</span>
<span class="token function">sudo</span> <span class="token function">docker</span> <span class="token builtin class-name">exec</span> <span class="token parameter variable">-it</span> ptfe_atlas /usr/bin/init.sh /app/scripts/wait-for-token -- <span class="token function">bash</span> <span class="token parameter variable">-i</span> <span class="token parameter variable">-c</span> <span class="token string">'cd /app &amp;&amp; ./bin/rails c'</span>
<span class="token comment">## 수정 최신 버전의 TFE에서는 Container 이름이 변경됨 (2022.6.21)</span>
<span class="token function">sudo</span> <span class="token function">docker</span> <span class="token builtin class-name">exec</span> <span class="token parameter variable">-it</span> tfe-atlas /usr/bin/init.sh /app/scripts/wait-for-token -- <span class="token function">bash</span> <span class="token parameter variable">-i</span> <span class="token parameter variable">-c</span> <span class="token string">'cd /app &amp;&amp; ./bin/rails c'</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-ruby line-numbers-mode" data-ext="rb"><pre v-pre class="language-ruby"><code>irb<span class="token punctuation">(</span>main<span class="token punctuation">)</span><span class="token operator">:</span><span class="token number">050</span><span class="token operator">:</span><span class="token number">0</span><span class="token operator">></span> admin_user <span class="token operator">=</span> User<span class="token punctuation">.</span>find_by<span class="token punctuation">(</span><span class="token symbol">username</span><span class="token operator">:</span> <span class="token string-literal"><span class="token string">"tfe-local-admin"</span></span><span class="token punctuation">)</span>
<span class="token operator">=></span> <span class="token comment">#&lt;User id: 33, email: "tfe-local-admin@test.com", username: "tfe-local-admin", is_admin: false, created_at: "2020-06-24 05:12:12", updated_at: "2020-07-01 09:12:25", suspended_at: nil, two_factor_delivery: nil, two_factor_sms_number: nil, two_factor_secret_key: nil, two_factor_recovery_index: 0, two_factor_recovery_secret_key: nil, two_factor_verified_at: nil, two_factor_enabled_at: nil, is_service_account: false, used_recovery_codes_encrypted: nil, last_auth_through_saml: nil, external_id: "user-361SGA3yMg3P1nGT", accepted_terms_at: nil, accepted_privacy_policy_at: nil, invitation_token: nil, invitation_created_at: nil, is_cyborg: false, onboarding_status: nil></span>
irb<span class="token punctuation">(</span>main<span class="token punctuation">)</span><span class="token operator">:</span><span class="token number">051</span><span class="token operator">:</span><span class="token number">0</span><span class="token operator">></span> admin_user<span class="token punctuation">.</span>password <span class="token operator">=</span> <span class="token string-literal"><span class="token string">'&lt;&lt;Password>>'</span></span>
<span class="token operator">=></span> <span class="token string-literal"><span class="token string">"&lt;&lt;Password>>"</span></span>
irb<span class="token punctuation">(</span>main<span class="token punctuation">)</span><span class="token operator">:</span><span class="token number">052</span><span class="token operator">:</span><span class="token number">0</span><span class="token operator">></span> admin_user<span class="token punctuation">.</span>password_confirmation <span class="token operator">=</span> <span class="token string-literal"><span class="token string">'&lt;&lt;Password>>'</span></span>
<span class="token operator">=></span> <span class="token string-literal"><span class="token string">"&lt;&lt;Password>>"</span></span>
irb<span class="token punctuation">(</span>main<span class="token punctuation">)</span><span class="token operator">:</span><span class="token number">053</span><span class="token operator">:</span><span class="token number">0</span><span class="token operator">></span> admin_user<span class="token punctuation">.</span>save
<span class="token number">2020</span><span class="token operator">-</span><span class="token number">07</span><span class="token operator">-</span><span class="token number">01</span> <span class="token number">10</span><span class="token operator">:</span><span class="token number">03</span><span class="token operator">:</span><span class="token number">32</span> <span class="token punctuation">[</span><span class="token constant">DEBUG</span><span class="token punctuation">]</span> <span class="token punctuation">{</span><span class="token symbol">:msg</span><span class="token operator">=></span><span class="token string-literal"><span class="token string">"SettingStorage::Postgres failed to look up setting 'basic.base_domain'"</span></span><span class="token punctuation">}</span>
<span class="token operator">=></span> <span class="token boolean">true</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="일반-사용자의-경우" tabindex="-1"><a class="header-anchor" href="#일반-사용자의-경우" aria-hidden="true">#</a> 일반 사용자의 경우</h2>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token function">sudo</span> <span class="token function">docker</span> <span class="token builtin class-name">exec</span> <span class="token parameter variable">-it</span> ptfe_atlas /usr/bin/init.sh /app/scripts/wait-for-token -- <span class="token function">bash</span> <span class="token parameter variable">-i</span> <span class="token parameter variable">-c</span> <span class="token string">'cd /app &amp;&amp; ./bin/rails c'</span>
user <span class="token operator">=</span> User.find_by<span class="token punctuation">(</span>email: <span class="token string">"user@example.com"</span><span class="token punctuation">)</span>
user.update<span class="token punctuation">(</span>:password <span class="token operator">=</span><span class="token operator">></span> <span class="token string">'&lt;&lt;PASSWORD>>'</span><span class="token punctuation">)</span>
user.save<span class="token operator">!</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="일반-사용자를-admin으로-승격이-필요할-때" tabindex="-1"><a class="header-anchor" href="#일반-사용자를-admin으로-승격이-필요할-때" aria-hidden="true">#</a> 일반 사용자를 Admin으로 승격이 필요할 때</h2>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token function">sudo</span> <span class="token function">docker</span> <span class="token builtin class-name">exec</span> <span class="token parameter variable">-it</span> ptfe_atlas /usr/bin/init.sh /app/scripts/wait-for-token -- <span class="token function">bash</span> <span class="token parameter variable">-i</span> <span class="token parameter variable">-c</span> <span class="token string">'cd /app &amp;&amp; ./bin/rails c'</span>
user <span class="token operator">=</span> User.find_by<span class="token punctuation">(</span>email: <span class="token string">"user@example.com"</span><span class="token punctuation">)</span>
user.update<span class="token punctuation">(</span>is_admin: <span class="token boolean">true</span><span class="token punctuation">)</span>
user.save<span class="token operator">!</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


